In [2]:
#word embedding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
#sample  sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
from tensorflow.keras.preprocessing.text import one_hot

In [ ]:
# Vocabulary size
voc_size=10000

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[7167, 1707, 2098, 4312], [7167, 1707, 2098, 9730], [7167, 1738, 2098, 5310], [3130, 1814, 1432, 430, 8427], [3130, 1814, 1432, 430, 6110], [2384, 7167, 6577, 2098, 9419], [2158, 9692, 5900, 430]]


In [7]:
import numpy as np

In [ ]:
sent_length=8 #can be changed depending on the sentence length 
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7167 1707 2098 4312]
 [   0    0    0    0 7167 1707 2098 9730]
 [   0    0    0    0 7167 1738 2098 5310]
 [   0    0    0 3130 1814 1432  430 8427]
 [   0    0    0 3130 1814 1432  430 6110]
 [   0    0    0 2384 7167 6577 2098 9419]
 [   0    0    0    0 2158 9692 5900  430]]


In [ ]:
dim=10 # can also be increased or decreased based on requirement 

In [10]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [11]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 202ms/step
[[[ 3.1926718e-02  7.2973855e-03  1.0301694e-03 -3.7084699e-02
   -1.6876139e-02 -4.7120500e-02  4.1881800e-03  2.3700539e-02
    3.9381657e-02  4.1615080e-02]
  [ 3.1926718e-02  7.2973855e-03  1.0301694e-03 -3.7084699e-02
   -1.6876139e-02 -4.7120500e-02  4.1881800e-03  2.3700539e-02
    3.9381657e-02  4.1615080e-02]
  [ 3.1926718e-02  7.2973855e-03  1.0301694e-03 -3.7084699e-02
   -1.6876139e-02 -4.7120500e-02  4.1881800e-03  2.3700539e-02
    3.9381657e-02  4.1615080e-02]
  [ 3.1926718e-02  7.2973855e-03  1.0301694e-03 -3.7084699e-02
   -1.6876139e-02 -4.7120500e-02  4.1881800e-03  2.3700539e-02
    3.9381657e-02  4.1615080e-02]
  [ 4.6804357e-02 -2.7984584e-02 -3.9216518e-02  1.5450906e-02
   -3.3771731e-02  3.0109096e-02 -4.0094960e-02 -2.5399303e-02
   -2.5179697e-02  1.6429637e-02]
  [ 1.1337686e-02  2.7468633e-02 -4.5396127e-02  4.5945909e-02
   -3.2769941e-02 -3.5577763e-02  1.4472257e-02 -3.7749350e-02
    7.1436651e-03 -3.3959351e-02]
 

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 7167, 1707, 2098, 4312], dtype=int32)

In [14]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
[[ 0.03192672  0.00729739  0.00103017 -0.0370847  -0.01687614 -0.0471205
   0.00418818  0.02370054  0.03938166  0.04161508]
 [ 0.03192672  0.00729739  0.00103017 -0.0370847  -0.01687614 -0.0471205
   0.00418818  0.02370054  0.03938166  0.04161508]
 [ 0.03192672  0.00729739  0.00103017 -0.0370847  -0.01687614 -0.0471205
   0.00418818  0.02370054  0.03938166  0.04161508]
 [ 0.03192672  0.00729739  0.00103017 -0.0370847  -0.01687614 -0.0471205
   0.00418818  0.02370054  0.03938166  0.04161508]
 [ 0.04680436 -0.02798458 -0.03921652  0.01545091 -0.03377173  0.0301091
  -0.04009496 -0.0253993  -0.0251797   0.01642964]
 [ 0.01133769  0.02746863 -0.04539613  0.04594591 -0.03276994 -0.03557776
   0.01447226 -0.03774935  0.00714367 -0.03395935]
 [-0.0351523   0.03670708 -0.01674495 -0.01480976 -0.00791173 -0.03697578
   0.04196762  0.01034515  0.03233875  0.00421345]
 [ 0.02956735 -0.04399956  0.03477744  0.04207187 -0.02837752 -0.02455977
  -0.02309135  0.0